version: "3.9"

services:

  traefik:
    container_name: &_tfk traefik
    image: traefik:v2.8
    build:
      context: *_tfk
    restart: always
    command:
      - --api=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --certificatesresolvers.cf.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.cf.acme.email=$CLOUDFLARE_EMAIL
      - --certificatesresolvers.cf.acme.storage=/acme.json
      - --certificatesresolvers.cf.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.cf.acme.dnsChallenge=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
      - local
    env_file:
      - .env
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
    volumes:
      - ./traefik/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      # global redirect to https
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

      # Dashboard
      - traefik.enable=true
      - traefik.http.routers.*_tfk.tls=true
      - traefik.http.routers.*_tfk.entrypoints=https
      - traefik.http.routers.*_tfk.rule=Host(`tf.$DOMAINNAME`)
      - traefik.http.routers.*_tfk.service=api@internal
      - traefik.http.routers.*_tfk.tls.certresolver=cf

      # BasicAuth
      - traefik.http.routers.*_tfk.middlewares=authtraefik
      - traefik.http.middlewares.authtraefik.basicauth.users=${BASICAUTH}

  backend:
    container_name: &_bk backend
    build: *_bk
    command: gunicorn app.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker -t 900
    user: "${PUID}:${PGID}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .env

  frontend:
    container_name: &_ft frontend
    build: *_ft
    command: nginx -g "daemon off;"
    volumes:
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - web
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.*_ft.tls=true
      - traefik.http.routers.*_ft.entrypoints=https
      - traefik.http.routers.*_ft.rule=Host(`app.$DOMAINNAME`)
      - traefik.http.services.*_ft.loadbalancer.server.port=80
      - traefik.http.routers.*_ft.tls.certresolver=cf

networks:
  web:
    name: "web"
    ipam:
      config:
        - subnet: 172.20.0.0/24
  local:
    name: "local"
    ipam:
      config:
        - subnet: 172.20.1.0/24
